apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: kubernetes-auth-server
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: kubernetes-auth-server
    spec:
      containers:
      - name: kubernetes-auth-server
        image: harshal0812/authserver
        imagePullPolicy: Always
        ports:
        - name: app-port
          containerPort: 3000
        env:
          - name: AUTH0_CLIENT_ID
            value: AUTH0_CLIENT_ID
          - name: AUTH0_DOMAIN
            value: AUTH0_DOMAIN_NAME
          - name: AUTH0_CALLBACK_URL
            value: http://authserver.kubernetesfederatedcluster.com/callback
          - name: AUTH0_API_ID
            value: https://AUTH0_DOMAIN_NAME/userinfo # change into your identifier
          - name: AUTH0_CONNECTION
            value: Username-Password-Authentication	 # auth0 user database connection
          - name: KUBERNETES_UI_HOST
            value: api.kubernetesfederatedcluster.com     # apiserver domain
          - name: APP_HOST
            value: authserver.kubernetesfederatedcluster.com
          - name: AUTH0_CLIENT_SECRET
            valueFrom:
              secretKeyRef:
                name: auth0-secrets
                key: AUTH0_CLIENT_SECRET
